const teluguMovies = [
    { title: "Baahubali", hero: "Prabhas", heroine: "Anushka", decade: "2010s", difficulty: "easy" },
    { title: "Pushpa", hero: "Allu Arjun", heroine: "Rashmika", decade: "2020s", difficulty: "easy" },
    { title: "RRR", hero: "Ram Charan", heroine: "Alia Bhatt", decade: "2020s", difficulty: "easy" },
    { title: "Magadheera", hero: "Ram Charan", heroine: "Kajal", decade: "2000s", difficulty: "easy" },
    { title: "Arya", hero: "Allu Arjun", heroine: "Anu Mehta", decade: "2000s", difficulty: "medium" },
    { title: "Pokiri", hero: "Mahesh Babu", heroine: "Ileana", decade: "2000s", difficulty: "easy" },
    { title: "Athadu", hero: "Mahesh Babu", heroine: "Trisha", decade: "2000s", difficulty: "medium" },
    { title: "Jalsa", hero: "Pawan Kalyan", heroine: "Ileana", decade: "2000s", difficulty: "medium" },
    { title: "Gabbar Singh", hero: "Pawan Kalyan", heroine: "Shruti Haasan", decade: "2010s", difficulty: "medium" },
    { title: "Julayi", hero: "Allu Arjun", heroine: "Ileana", decade: "2010s", difficulty: "medium" },
    { title: "Race Gurram", hero: "Allu Arjun", heroine: "Shruti Haasan", decade: "2010s", difficulty: "easy" },
    { title: "Srimanthudu", hero: "Mahesh Babu", heroine: "Shruti Haasan", decade: "2010s", difficulty: "easy" },
    { title: "Bharaate", hero: "Sriimurali", heroine: "Bhavana", decade: "2010s", difficulty: "hard" },
    { title: "Temper", hero: "Jr NTR", heroine: "Kajal", decade: "2010s", difficulty: "medium" },
    { title: "Brindavanam", hero: "Jr NTR", heroine: "Samantha", decade: "2010s", difficulty: "medium" },
    { title: "Julayi", hero: "Allu Arjun", heroine: "Ileana", decade: "2010s", difficulty: "medium" },
    { title: "Nannaku Prematho", hero: "Jr NTR", heroine: "Rakul Preet", decade: "2010s", difficulty: "medium" },
    { title: "Baahubali 2", hero: "Prabhas", heroine: "Anushka", decade: "2010s", difficulty: "easy" },
    { title: "Eega", hero: "Nani", heroine: "Samantha", decade: "2010s", difficulty: "easy" },
    { title: "Puri", hero: "Nani", heroine: "Shriya", decade: "2010s", difficulty: "hard" },
    { title: "Ye Maaya Chesave", hero: "Naga Chaitanya", heroine: "Samantha", decade: "2010s", difficulty: "medium" },
    { title: "Manam", hero: "Naga Chaitanya", heroine: "Samantha", decade: "2010s", difficulty: "medium" },
    { title: "Oopiri", hero: "Naga Chaitanya", heroine: "Tamannaah", decade: "2010s", difficulty: "medium" },
    { title: "Akhil", hero: "Akhil Akkineni", heroine: "Sayesha", decade: "2010s", difficulty: "medium" },
    { title: "Sarrainodu", hero: "Allu Arjun", heroine: "Rakul Preet", decade: "2010s", difficulty: "easy" },
    { title: "DJ Duvvada Jagannadham", hero: "Allu Arjun", heroine: "Pooja Hegde", decade: "2010s", difficulty: "medium" },
    { title: "Ala Vaikunthapurramuloo", hero: "Allu Arjun", heroine: "Pooja Hegde", decade: "2020s", difficulty: "easy" },
    { title: "Uppena", hero: "Vaishnav Tej", heroine: "Krithi Shetty", decade: "2020s", difficulty: "medium" },
    { title: "Bheemla Nayak", hero: "Pawan Kalyan", heroine: "Nithya Menen", decade: "2020s", difficulty: "medium" },
    { title: "Vakeel Saab", hero: "Pawan Kalyan", heroine: "Nivetha Thomas", decade: "2020s", difficulty: "medium" },
    { title: "Krack", hero: "Ravi Teja", heroine: "Shruti Haasan", decade: "2020s", difficulty: "medium" },
    { title: "Khiladi", hero: "Ravi Teja", heroine: "Meenakshi Chaudhary", decade: "2020s", difficulty: "hard" },
    { title: "Ramarao On Duty", hero: "Ravi Teja", heroine: "Divyansha Kaushik", decade: "2020s", difficulty: "hard" },
    { title: "Bangarraju", hero: "Naga Chaitanya", heroine: "Krithi Shetty", decade: "2020s", difficulty: "medium" },
    { title: "Thank You", hero: "Naga Chaitanya", heroine: "Raashii Khanna", decade: "2020s", difficulty: "hard" },
    { title: "Ante Sundaraniki", hero: "Nani", heroine: "Nazriya", decade: "2020s", difficulty: "medium" },
    { title: "Shyam Singha Roy", hero: "Nani", heroine: "Sai Pallavi", decade: "2020s", difficulty: "medium" },
    { title: "Tuck Jagadish", hero: "Nani", heroine: "Ritu Varma", decade: "2020s", difficulty: "medium" },
    { title: "Dasara", hero: "Nani", heroine: "Keerthy Suresh", decade: "2020s", difficulty: "medium" },
    { title: "Hi Nanna", hero: "Nani", heroine: "Mrunal Thakur", decade: "2020s", difficulty: "easy" },
    { title: "Sarkaru Vaari Paata", hero: "Mahesh Babu", heroine: "Keerthy Suresh", decade: "2020s", difficulty: "easy" },
    { title: "Guntur Kaaram", hero: "Mahesh Babu", heroine: "Sreeleela", decade: "2020s", difficulty: "medium" },
    { title: "Kalki 2898 AD", hero: "Prabhas", heroine: "Deepika Padukone", decade: "2020s", difficulty: "easy" },
    { title: "Salaar", hero: "Prabhas", heroine: "Shruti Haasan", decade: "2020s", difficulty: "easy" },
    { title: "Radhe Shyam", hero: "Prabhas", heroine: "Pooja Hegde", decade: "2020s", difficulty: "medium" },
    { title: "Adipurush", hero: "Prabhas", heroine: "Kriti Sanon", decade: "2020s", difficulty: "medium" },
    { title: "Vikramarkudu", hero: "Ravi Teja", heroine: "Anushka", decade: "2000s", difficulty: "easy" },
    { title: "Don", hero: "Ravi Teja", heroine: "Ayesha Takia", decade: "2000s", difficulty: "medium" },
    { title: "Kick", hero: "Ravi Teja", heroine: "Ileana", decade: "2000s", difficulty: "easy" },
    { title: "Mirapakay", hero: "Ravi Teja", heroine: "Richa Gangopadhyay", decade: "2010s", difficulty: "medium" },
    { title: "Oosaravelli", hero: "Jr NTR", heroine: "Tamannah", decade: "2010s", difficulty: "medium" },
    { title: "Dammu", hero: "Jr NTR", heroine: "Trisha", decade: "2010s", difficulty: "medium" },
    { title: "Ramayya Vasthavayya", hero: "Jr NTR", heroine: "Samantha", decade: "2010s", difficulty: "medium" },
    { title: "Aagadu", hero: "Mahesh Babu", heroine: "Tamannaah", decade: "2010s", difficulty: "medium" },
    { title: "Dookudu", hero: "Mahesh Babu", heroine: "Samantha", decade: "2010s", difficulty: "easy" },
    { title: "1 Nenokkadine", hero: "Mahesh Babu", heroine: "Kriti Sanon", decade: "2010s", difficulty: "medium" },
    { title: "Spyder", hero: "Mahesh Babu", heroine: "Rakul Preet", decade: "2010s", difficulty: "medium" },
    { title: "Maharshi", hero: "Mahesh Babu", heroine: "Pooja Hegde", decade: "2010s", difficulty: "medium" },
    { title: "Sarileru Neekevvaru", hero: "Mahesh Babu", heroine: "Rashmika", decade: "2020s", difficulty: "easy" },
    { title: "Tagore", hero: "Chiranjeevi", heroine: "Shriya", decade: "2000s", difficulty: "medium" },
    { title: "Indra", hero: "Chiranjeevi", heroine: "Sonali Bendre", decade: "2000s", difficulty: "medium" },
    { title: "Stalin", hero: "Chiranjeevi", heroine: "Trisha", decade: "2000s", difficulty: "medium" },
    { title: "Khaidi No 150", hero: "Chiranjeevi", heroine: "Kajal", decade: "2010s", difficulty: "easy" },
    { title: "Sye Raa", hero: "Chiranjeevi", heroine: "Nayanthara", decade: "2010s", difficulty: "easy" },
    { title: "Waltair Veerayya", hero: "Chiranjeevi", heroine: "Shruti Haasan", decade: "2020s", difficulty: "medium" },
    { title: "Bholaa Shankar", hero: "Chiranjeevi", heroine: "Tamannaah", decade: "2020s", difficulty: "hard" },
    { title: "GodFather", hero: "Chiranjeevi", heroine: "Nayanthara", decade: "2020s", difficulty: "medium" },
    { title: "Komaram Puli", hero: "Pawan Kalyan", heroine: "Trisha", decade: "2000s", difficulty: "medium" },
    { title: "Panjaa", hero: "Pawan Kalyan", heroine: "Sarah Jane Dias", decade: "2010s", difficulty: "hard" },
    { title: "Attarintiki Daredi", hero: "Pawan Kalyan", heroine: "Samantha", decade: "2010s", difficulty: "easy" },
    { title: "Agnyaathavaasi", hero: "Pawan Kalyan", heroine: "Keerthy Suresh", decade: "2010s", difficulty: "medium" },
    { title: "Trivikram", hero: "Pawan Kalyan", heroine: "Pooja Hegde", decade: "2010s", difficulty: "medium" },
    { title: "Aravinda Sametha", hero: "Jr NTR", heroine: "Pooja Hegde", decade: "2010s", difficulty: "medium" },
    { title: "Jai Lava Kusa", hero: "Jr NTR", heroine: "Raashi Khanna", decade: "2010s", difficulty: "medium" },
    { title: "Janatha Garage", hero: "Jr NTR", heroine: "Samantha", decade: "2010s", difficulty: "medium" },
    { title: "Devara", hero: "Jr NTR", heroine: "Janhvi Kapoor", decade: "2020s", difficulty: "easy" },
    { title: "Arya 2", hero: "Allu Arjun", heroine: "Kajal", decade: "2000s", difficulty: "easy" },
    { title: "Vedam", hero: "Allu Arjun", heroine: "Anushka", decade: "2010s", difficulty: "medium" },
    { title: "Badrinath", hero: "Allu Arjun", heroine: "Tamannah", decade: "2010s", difficulty: "medium" },
    { title: "Iddarammayilatho", hero: "Allu Arjun", heroine: "Amala Paul", decade: "2010s", difficulty: "medium" },
    { title: "S/O Satyamurthy", hero: "Allu Arjun", heroine: "Samantha", decade: "2010s", difficulty: "medium" },
    { title: "Rudhramadevi", hero: "Allu Arjun", heroine: "Anushka", decade: "2010s", difficulty: "medium" },
    { title: "Pushpa 2", hero: "Allu Arjun", heroine: "Rashmika", decade: "2020s", difficulty: "easy" },
    { title: "Kondapolam", hero: "Vaishnav Tej", heroine: "Rakul Preet", decade: "2020s", difficulty: "hard" },
    { title: "Ranga Ranga Vaibhavanga", hero: "Vaishnav Tej", heroine: "Ketika Sharma", decade: "2020s", difficulty: "hard" },
    { title: "Kushi", hero: "Vaishnav Tej", heroine: "Samantha", decade: "2020s", difficulty: "medium" },
    { title: "Thandel", hero: "Naga Chaitanya", heroine: "Sai Pallavi", decade: "2020s", difficulty: "medium" },
    { title: "Gangs of Godavari", hero: "Vishwak Sen", heroine: "Anjali", decade: "2020s", difficulty: "medium" },
    { title: "Tillu Square", hero: "Siddu Jonnalagadda", heroine: "Anupama Parameswaran", decade: "2020s", difficulty: "medium" },
    { title: "HanuMan", hero: "Teja Sajja", heroine: "Amritha Aiyer", decade: "2020s", difficulty: "easy" },
    { title: "Guntur Kaaram", hero: "Mahesh Babu", heroine: "Sreeleela", decade: "2020s", difficulty: "medium" },
    { title: "Skanda", hero: "Ram Pothineni", heroine: "Sreeleela", decade: "2020s", difficulty: "medium" },
    { title: "Eagle", hero: "Ravi Teja", heroine: "Kavya Thapar", decade: "2020s", difficulty: "hard" },
    { title: "Tiger Nageswara Rao", hero: "Ravi Teja", heroine: "Nupur Sanon", decade: "2020s", difficulty: "medium" },
    { title: "Retro", hero: "Suriya", heroine: "Pooja Hegde", decade: "2020s", difficulty: "medium" },
  ];
  
  module.exports = teluguMovies;